CREATE TABLE IF NOT EXISTS consultas
(id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
dataHoraPaciente VARCHAR(100) NOT NULL,
dataHoraDentista VARCHAR(100) NOT NULL,
dataHoraConsulta VARCHAR(100) NOT NULL,
dentista VARCHAR(100) NOT NULL,
paciente VARCHAR(100) NOT NULL);